name: qxz
on:
  workflow_dispatch:
  schedule: 
    # 代表国际标准时间21点30分，北京时间需要+8小时，代表北京时间上午5点30分点运行
    - cron: '26 00 * * *'
jobs:
#将工作流程中运行的所有作业组合在一起
  build:
  #定义名为 build 的作业，子键将定义作业的属性 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Node.js #添加nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'  #nodejs版本
      - name: Set timezone #设置时间
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - name: Install Dependency #添加环境
        run: |
          npm install
          npm install got
          npm install tough-cookie
      - name: qxz #运行名称
        env:    #获取环境变量设置名称
            xqzck: ${{ secrets.XQZCK }}
        run: |  #运行脚本
          node ./scripts/cx.js #脚本存在根目录的qxz.js不在根目录要用./文件夹名/.js 
